// Generated by FlutterFire CLI for project: diplomkauniverse
// Re-run: dart pub global run flutterfire_cli:flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured {
    const key = String.fromEnvironment('FIREBASE_API_KEY', defaultValue: '');
    if (key.isNotEmpty) return true;
    return !android.apiKey.startsWith('YOUR_');
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5LQpLyoi4CDm2GeU_0PCnSJoa6iBzu_c',
    appId: '1:367874596322:web:3c24c865ea87495f892dbb',
    messagingSenderId: '367874596322',
    projectId: 'diplomkauniverse',
    authDomain: 'diplomkauniverse.firebaseapp.com',
    storageBucket: 'diplomkauniverse.firebasestorage.app',
    measurementId: 'G-KTX0CD9826',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbogQ65Ds83jv2aZW_4-FkfqZxDcuo-r4',
    appId: '1:367874596322:android:53cf6387ab419316892dbb',
    messagingSenderId: '367874596322',
    projectId: 'diplomkauniverse',
    storageBucket: 'diplomkauniverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.diplomka',
  );
}